services:
  notification-service:
    image: voloshmiak/notification-service:0.0.1
    container_name: notification-service
    hostname: notification-service
    networks:
      - ecommerce-network
    restart: on-failure
    depends_on:
      kafka-init:
        condition: service_completed_successfully
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}

  user-service:
    image: voloshmiak/user-service:0.0.7
    container_name: user-service
    hostname: user-service
    networks:
      - ecommerce-network
    ports:
      - ":8080"
    restart: on-failure
    depends_on:
      postgres-user:
        condition: service_healthy
      notification-service:
        condition: service_started
    environment:
      DB_HOST: postgres-user
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: postgres
      SERVER_PORT: 8080
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092

  product-catalog-service:
    image: voloshmiak/product-catalog-service:0.0.4
    container_name: product-catalog-service
    hostname: product-catalog-service
    networks:
      - ecommerce-network
    ports:
      - ":8080"
    restart: on-failure
    depends_on:
      mongodb:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      user-service:
        condition: service_started
    environment:
      - KAFKA_HOST=kafka
      - KAFKA_PORT=29092
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB_NAME=ecommerce
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=password
      - SERVER_PORT=8080
      - ELASTIC_HOST=elasticsearch
      - ELASTIC_PORT=9200

  shopping-cart-service:
    image: voloshmiak/shopping-cart-service:0.0.5
    container_name: shopping-cart-service
    hostname: shopping-cart-service
    networks:
      - ecommerce-network
    ports:
      - ":8080"
    restart: on-failure
    depends_on:
      redis:
        condition: service_healthy
      product-catalog-service:
        condition: service_started
    environment:
      DB_HOST: redis
      DB_PORT: 6379
      SERVER_PORT: 8080
      PRODUCT_CATALOG_HOST: product-catalog-service
      PRODUCT_CATALOG_PORT: 8080

  payment-service:
    image: voloshmiak/payment-service:0.0.7
    container_name: payment-service
    hostname: payment-service
    networks:
      - ecommerce-network
    ports:
      - ":8080"
    restart: on-failure
    depends_on:
      postgres-payment:
        condition: service_healthy
      shopping-cart-service:
        condition: service_started
    environment:
      DB_HOST: postgres-payment
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: postgres
      SERVER_PORT: 8080
      CART_HOST: shopping-cart-service
      CART_PORT: 8080
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
      STRIPE_SECRET: ${STRIPE_SECRET}

  order-service:
    image: voloshmiak/order-service:0.0.8
    container_name: order-service
    hostname: order-service
    networks:
      - ecommerce-network
    ports:
      - ":8080"
    restart: on-failure
    depends_on:
      postgres-order:
        condition: service_healthy
      payment-service:
        condition: service_started
    environment:
      DB_HOST: postgres-order
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: postgres
      SERVER_PORT: 8080
      CART_HOST: shopping-cart-service
      CART_PORT: 8080
      USER_HOST: user-service
      USER_PORT: 8080
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092

  postgres-user:
    image: postgres:15
    container_name: postgres-user
    hostname: postgres-user
    networks:
      - ecommerce-network
    ports:
      - ":5432"
    volumes:
      - postgres-user-data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=md5
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "$${POSTGRES_USER}", "-d", "$${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 60s

  postgres-order:
    image: postgres:15
    container_name: postgres-order
    hostname: postgres-order
    networks:
      - ecommerce-network
    ports:
      - ":5432"
    volumes:
      - postgres-order-data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=md5
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "$${POSTGRES_USER}", "-d", "$${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 60s

  postgres-payment:
    image: postgres:15
    container_name: postgres-payment
    hostname: postgres-payment
    networks:
      - ecommerce-network
    ports:
      - ":5432"
    volumes:
      - postgres-payment-data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=md5
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "$${POSTGRES_USER}", "-d", "$${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 60s

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    networks:
      - ecommerce-network
    ports:
      - ":27017"
    volumes:
      - mongodb-data:/data/db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "'db.runCommand({ping:1}).ok'"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 120s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: elasticsearch
    hostname: elasticsearch
    networks:
      - ecommerce-network
    ports:
      - ":9200"
      - ":9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    healthcheck:
      test: ["CMD", "curl", "-f",  "localhost:9200/_cluster/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 120s

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    networks:
      - ecommerce-network
    ports:
      - ":6379"
    volumes:
      - redis-data:/data
    restart: always
    environment:
      - REDIS_USER=user
      - REDIS_USER_PASSWORD=password
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

  kafka:
    image: confluentinc/cp-kafka:8.1.0
    container_name: kafka
    hostname: kafka
    networks:
      - ecommerce-network
    ports:
      - ":9092"
      - ":29092"
    restart: always
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://kafka:9093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 60s

  kafka-init:
    image: confluentinc/cp-kafka:8.1.0
    container_name: kafka-init
    networks:
      - ecommerce-network
    volumes:
      - ./scripts/create-kafka-topics.sh:/usr/local/bin/create-kafka-topics.sh
    command: /usr/local/bin/create-kafka-topics.sh
    depends_on:
      kafka:
        condition: service_healthy

  kong-gateway:
    image: voloshmiak/my-custom-kong:0.0.1
    container_name: kong-gateway
    hostname: kong-gateway
    networks:
      - ecommerce-network
    ports:
      - "8000:8000"
    volumes:
      - ./kong:/kong/declarative/
      - ./kong/kong-data/tmp:/tmp
      - ./kong/kong-data/prefix:/var/run/kong
      - ./nexus-contracts/proto:/kong/proto
      - ./nexus-contracts/proto/google/api:/usr/local/kong/include/google/api
    restart: always
    environment:
      KONG_PREFIX: /var/run/kong
      KONG_DATABASE: off
      KONG_STATUS_LISTEN: 0.0.0.0:8100
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yaml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_LICENSE_DATA: "${KONG_LICENSE_DATA}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8100/status/ready" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  frontend:
    image: voloshmiak/frontend:0.0.1
    container_name: frontend
    hostname: frontend
    networks:
      - ecommerce-network
    ports:
      - "3000:80"
    restart: always
    environment:
      - VUE_APP_API_BASE_URL=http://34.141.60.44:8000/api/v1
      - VUE_APP_STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE}
      - VUE_APP_DEBUG=false

networks:
  ecommerce-network:
    driver: bridge

volumes:
  postgres-user-data:
  postgres-order-data:
  postgres-payment-data:
  mongodb-data:
  es-data:
  redis-data: