apiVersion: v1
kind: Secret
metadata:
  name: service-secrets
  namespace: services
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
  
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "password"
  
  REDIS_USER: "user"
  REDIS_USER_PASSWORD: "password"
  
  STRIPE_SECRET: "YOUR_API_KEY_HERE"
  SENDGRID_API_KEY: "YOUR_API_KEY_HERE"
---
apiVersion: v1
kind: Secret
metadata:
  name: data-secrets
  namespace: data
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
  
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "password"
  
  REDIS_USER: "user"
  REDIS_USER_PASSWORD: "password"
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: api
type: Opaque
stringData:
  STRIPE_PUBLISHABLE_KEY: "YOUR_STRIPE_PUBLISHABLE_KEY_HERE"
