apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart-deployment
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-cart
  template:
    metadata:
      labels:
        app: shopping-cart
    spec:
      containers:
        - name: shopping-cart-service
          image: voloshmiak/shopping-cart-service:0.0.5
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom: { configMapKeyRef: { name: service-config, key: CART_DB_HOST } }
            - name: DB_PORT
              valueFrom: { configMapKeyRef: { name: service-config, key: CART_DB_PORT } }
            - name: SERVER_PORT
              valueFrom: { configMapKeyRef: { name: service-config, key: CART_SERVER_PORT } }
            - name: PRODUCT_CATALOG_HOST
              valueFrom: { configMapKeyRef: { name: service-config, key: CART_PRODUCT_CATALOG_HOST } }
            - name: PRODUCT_CATALOG_PORT
              valueFrom: { configMapKeyRef: { name: service-config, key: CART_PRODUCT_CATALOG_PORT } }
            - name: DB_PASSWORD
              valueFrom: { secretKeyRef: { name: service-secrets, key: REDIS_USER_PASSWORD} }