apiVersion: v1
kind: Service
metadata:
  name: product-catalog-service
  namespace: services
spec:
  type: ClusterIP
  selector:
    app: product-catalog
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080