apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-service
  namespace: services
spec:
  type: ClusterIP
  selector:
    app: shopping-cart
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080